spring:
  datasource:
    url: jdbc:mysql://localhost/testserver
    username: root
    password: Ehealthsqlserver1
    driverClassName: com.mysql.cj.jdbc.Driver
    max-active: 15
  jpa:
    properties:
      hibernate:
        dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirMySQLDialect
      ddl-auto: update
  testserver:
    datasource:
      url: jdbc:mysql://localhost/testserver
      username: root
      password: Ehealthsqlserver1
      driverClassName: com.mysql.cj.jdbc.Driver
      max-active: 15
      hikari:
        maximum-pool-size: 10
    jpa:
      properties:
        hibernate.search.enabled: false
        hibernate.format_sql: true
        hibernate.show_sql: true
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect