spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dte?currentSchema=hapi_fhir
    driver-class-name: org.postgresql.Driver
    username: myuser
    password: mypassword
service:
  dte-backend:
    endpoint: http://localhost:9090
    username: management
    password: management