spring:
  datasource:
    url: jdbc:postgresql://10.20.50.204:5432/ehp-fhir-testserver
    username: hp-fhir-testserver
    password: cU8.Q4_askLeAP4Juq4E*UQn6_HhMZxqYvn
    driverClassName: org.postgresql.Driver
    max-active: 15
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      ddl-auto: update
  testserver:
    datasource:
      url: jdbc:postgresql://10.20.50.204:5432/ehp-fhir-testserver
      username: ehp-fhir-testserver
      password: cU8.Q4_askLeAP4Juq4E*UQn6_HhMZxqYvn
      driverClassName: org.postgresql.Driver
      max-active: 15
      hikari:
        maximum-pool-size: 10
    jpa:
      properties:
        hibernate.search.enabled: false
        hibernate.format_sql: true
        hibernate.show_sql: true
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect