spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/dte?currentSchema=hapi_fhir
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    max-active: 15
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      ddl-auto: update
service:
  dte-backend:
    endpoint: https://dte-dev.ehealth.fgov.be
    username: ${service.dte-backend.username}
    password: ${service.dte-backend.password}